import React, { useState } from 'react';
import {
    Grid,
    Table,
    TableHeaderRow,
    TableFilterRow,
    TableColumnResizing,
    PagingPanel,
    TableColumnVisibility,
    Toolbar,
    ColumnChooser
} from '@devexpress/dx-react-grid-material-ui';
import {
    FilteringState,
    IntegratedFiltering,
    SortingState,
    IntegratedSorting,
    PagingState,
    IntegratedPaging,
    ColumnChooserState
} from '@devexpress/dx-react-grid';

const columns = [
    { name: 'id', title: 'ID' },
    { name: 'name', title: 'Name' },
    { name: 'age', title: 'Age' },
    { name: 'email', title: 'Email' },
    { name: 'phone', title: 'Phone' },
    { name: 'address', title: 'Address' },
    { name: 'city', title: 'City' },
    { name: 'state', title: 'State' },
    { name: 'zip', title: 'ZIP Code' },
    { name: 'country', title: 'Country' },
    { name: 'company', title: 'Company' },
    { name: 'position', title: 'Position' },
    { name: 'department', title: 'Department' },
    { name: 'salary', title: 'Salary' },
    { name: 'hireDate', title: 'Hire Date' },
    { name: 'manager', title: 'Manager' },
    { name: 'status', title: 'Status' },
    { name: 'location', title: 'Location' },
    { name: 'experience', title: 'Experience (Years)' },
    { name: 'education', title: 'Education' },
    { name: 'skills', title: 'Skills' },
    { name: 'certifications', title: 'Certifications' },
    { name: 'projects', title: 'Projects' },
    { name: 'performance', title: 'Performance Rating' }
];

const rows = [
    {
        id: 1,
        name: 'John Doe',
        age: 25,
        email: 'john@example.com',
        phone: '555-1234',
        address: '123 Main St',
        city: 'Anytown',
        state: 'CA',
        zip: '12345',
        country: 'USA',
        company: 'Tech Corp',
        position: 'Developer',
        department: 'Engineering',
        salary: 60000,
        hireDate: '2021-01-10',
        manager: 'Bob Johnson',
        status: 'Active',
        location: 'New York',
        experience: 2,
        education: 'B.Sc. Computer Science',
        skills: 'JavaScript, React, Node.js',
        certifications: 'AWS Certified Developer',
        projects: 'Project A, Project B',
        performance: 'Excellent'
    },
    {
        id: 2,
        name: 'Jane Doe',
        age: 30,
        email: 'jane@example.com',
        phone: '555-5678',
        address: '456 Oak St',
        city: 'Othertown',
        state: 'TX',
        zip: '67890',
        country: 'USA',
        company: 'Design Studio',
        position: 'Designer',
        department: 'Creative',
        salary: 70000,
        hireDate: '2019-03-12',
        manager: 'Alice Brown',
        status: 'Active',
        location: 'San Francisco',
        experience: 5,
        education: 'B.A. Graphic Design',
        skills: 'Photoshop, Illustrator, Figma',
        certifications: 'Adobe Certified Expert',
        projects: 'Project C, Project D',
        performance: 'Good'
    },
    {
        id: 3,
        name: 'Mary Smith',
        age: 35,
        email: 'mary@example.com',
        phone: '555-9012',
        address: '789 Pine St',
        city: 'Sometown',
        state: 'NY',
        zip: '11223',
        country: 'USA',
        company: 'Business Inc',
        position: 'Manager',
        department: 'Operations',
        salary: 80000,
        hireDate: '2018-07-15',
        manager: 'Charlie Green',
        status: 'On Leave',
        location: 'Chicago',
        experience: 10,
        education: 'MBA',
        skills: 'Leadership, Communication, Strategy',
        certifications: 'PMP',
        projects: 'Project E, Project F',
        performance: 'Very Good'
    },
    {
        id: 4,
        name: 'James Johnson',
        age: 40,
        email: 'james@example.com',
        phone: '555-3456',
        address: '101 Maple St',
        city: 'Anycity',
        state: 'FL',
        zip: '33445',
        country: 'USA',
        company: 'Marketing Hub',
        position: 'Sales Executive',
        department: 'Sales',
        salary: 55000,
        hireDate: '2020-09-01',
        manager: 'Diana White',
        status: 'Active',
        location: 'Dallas',
        experience: 12,
        education: 'B.B.A. Marketing',
        skills: 'Sales, Negotiation, CRM',
        certifications: 'Certified Sales Professional',
        projects: 'Project G, Project H',
        performance: 'Excellent'
    },
    {
        id: 5,
        name: 'Patricia Brown',
        age: 45,
        email: 'patricia@example.com',
        phone: '555-7890',
        address: '202 Cedar St',
        city: 'Everytown',
        state: 'IL',
        zip: '55667',
        country: 'USA',
        company: 'Design Studio',
        position: 'HR Manager',
        department: 'Human Resources',
        salary: 90000,
        hireDate: '2015-06-15',
        manager: 'Evan Black',
        status: 'Active',
        location: 'San Francisco',
        experience: 20,
        education: 'M.Sc. Human Resources',
        skills: 'Recruitment, Employee Relations, HRIS',
        certifications: 'SHRM-CP',
        projects: 'Project I, Project J',
        performance: 'Very Good'
    },
    {
        id: 6,
        name: 'Robert Davis',
        age: 50,
        email: 'robert@example.com',
        phone: '555-9876',
        address: '303 Birch St',
        city: 'Somecity',
        state: 'WA',
        zip: '77889',
        country: 'USA',
        company: 'Tech Corp',
        position: 'Software Engineer',
        department: 'Engineering',
        salary: 95000,
        hireDate: '2017-08-01',
        manager: 'Bob Johnson',
        status: 'Active',
        location: 'Seattle',
        experience: 15,
        education: 'B.Sc. Computer Science',
        skills: 'Java, Spring, Microservices',
        certifications: 'Oracle Certified Professional',
        projects: 'Project O, Project P',
        performance: 'Very Good'
    },
    {
        id: 7,
        name: 'Linda Martinez',
        age: 55,
        email: 'linda@example.com',
        phone: '555-5432',
        address: '404 Spruce St',
        city: 'Anyville',
        state: 'OR',
        zip: '99001',
        country: 'USA',
        company: 'Marketing Hub',
        position: 'CEO',
        department: 'Executive',
        salary: 150000,
        hireDate: '2010-11-22',
        manager: '-',
        status: 'Active',
        location: 'Dallas',
        experience: 25,
        education: 'MBA',
        skills: 'Leadership, Strategy, Management',
        certifications: 'Executive Leadership Program',
        projects: 'Project M, Project N',
        performance: 'Excellent'
    },
    {
        id: 8,
        name: 'Michael Wilson',
        age: 60,
        email: 'michael@example.com',
        phone: '555-2109',
        address: '505 Spruce St',
        city: 'Everycity',
        state: 'NV',
        zip: '11234',
        country: 'USA',
        company: 'Tech Corp',
        position: 'CTO',
        department: 'Executive',
        salary: 200000,
        hireDate: '2010-04-30',
        manager: '-',
        status: 'Active',
        location: 'San Francisco',
        experience: 18,
        education: 'Ph.D. Computer Science',
        skills: 'Leadership, Technology Strategy, Innovation',
        certifications: 'Certified Technology Officer',
        projects: 'Project S, Project T',
        performance: 'Excellent'
    },
    {
        id: 9,
        name: 'Barbara Anderson',
        age: 65,
        email: 'barbara@example.com',
        phone: '555-6543',
        address: '606 Redwood St',
        city: 'Anyburg',
        state: 'CO',
        zip: '22345',
        country: 'USA',
        company: 'Tech Corp',
        position: 'Data Scientist',
        department: 'Data Science',
        salary: 105000,
        hireDate: '2018-01-15',
        manager: 'Leo Sun',
        status: 'Active',
        location: 'New York',
        experience: 8,
        education: 'M.Sc. Data Science',
        skills: 'Python, Machine Learning, Data Analysis',
        certifications: 'Certified Data Scientist',
        projects: 'Project Q, Project R',
        performance: 'Excellent'
    },
    {
        id: 10,
        name: 'William Thomas',
        age: 70,
        email: 'william@example.com',
        phone: '555-3210',
        address: '707 Fir St',
        city: 'Someburg',
        state: 'AZ',
        zip: '33456',
        country: 'USA',
        company: 'Tech Corp',
        position: 'CTO',
        department: 'Executive',
        salary: 105000,
        hireDate: '2011-01-10',
        manager: '-',
        status: 'Active',
        location: 'San Francisco',
        experience: 18,
        education: 'Ph.D. Computer Science',
        skills: 'Leadership, Technology Strategy, Innovation',
        certifications: 'Certified Technology Officer',
        projects: 'Project S, Project T',
        performance: 'Excellent'
    },
    {
        id: 11,
        name: 'David Clark',
        age: 26,
        email: 'david@example.com',
        phone: '555-1111',
        address: '808 Elm St',
        city: 'Sometown',
        state: 'CA',
        zip: '56789',
        country: 'USA',
        company: 'Tech Corp',
        position: 'Junior Developer',
        department: 'Engineering',
        salary: 60000,
        hireDate: '2020-02-10',
        manager: 'John Doe',
        status: 'Active',
        location: 'New York',
        experience: 3,
        education: 'B.Sc. Computer Science',
        skills: 'JavaScript, React',
        certifications: 'None',
        projects: 'Project Z',
        performance: 'Good'
    },
    {
        id: 12,
        name: 'Susan Taylor',
        age: 35,
        email: 'susan@example.com',
        phone: '555-2222',
        address: '909 Pine St',
        city: 'Anycity',
        state: 'TX',
        zip: '67891',
        country: 'USA',
        company: 'Finance Corp',
        position: 'Finance Manager',
        department: 'Finance',
        salary: 85000,
        hireDate: '2017-05-15',
        manager: 'David Clark',
        status: 'Active',
        location: 'Dallas',
        experience: 10,
        education: 'MBA',
        skills: 'Financial Analysis, Accounting',
        certifications: 'CPA',
        projects: 'Project F',
        performance: 'Excellent'
    },
    {
        id: 13,
        name: 'Michael Allen',
        age: 28,
        email: 'michael@example.com',
        phone: '555-3333',
        address: '111 Oak St',
        city: 'Sometown',
        state: 'FL',
        zip: '33446',
        country: 'USA',
        company: 'Retail Hub',
        position: 'Sales Manager',
        department: 'Sales',
        salary: 75000,
        hireDate: '2019-07-01',
        manager: 'James Johnson',
        status: 'Active',
        location: 'Chicago',
        experience: 7,
        education: 'B.B.A. Marketing',
        skills: 'CRM, Sales',
        certifications: 'Certified Sales Expert',
        projects: 'Project H',
        performance: 'Good'
    },
    {
        id: 14,
        name: 'Laura Evans',
        age: 29,
        email: 'laura@example.com',
        phone: '555-4444',
        address: '222 Maple St',
        city: 'Anytown',
        state: 'IL',
        zip: '55668',
        country: 'USA',
        company: 'Tech Corp',
        position: 'Software Engineer',
        department: 'Engineering',
        salary: 95000,
        hireDate: '2021-03-10',
        manager: 'Robert Davis',
        status: 'Active',
        location: 'San Francisco',
        experience: 5,
        education: 'M.Sc. Computer Science',
        skills: 'Java, Spring Boot',
        certifications: 'Oracle Certified Developer',
        projects: 'Project P',
        performance: 'Very Good'
    },
    {
        id: 15,
        name: 'Paul Harris',
        age: 32,
        email: 'paul@example.com',
        phone: '555-5555',
        address: '333 Birch St',
        city: 'Sometown',
        state: 'NY',
        zip: '11224',
        country: 'USA',
        company: 'Finance Corp',
        position: 'Data Analyst',
        department: 'Data Science',
        salary: 78000,
        hireDate: '2016-06-12',
        manager: 'Barbara Anderson',
        status: 'Active',
        location: 'Seattle',
        experience: 8,
        education: 'B.Sc. Data Science',
        skills: 'SQL, Python, Excel',
        certifications: 'Data Analyst',
        projects: 'Project Q',
        performance: 'Good'
    },
    {
        id: 16,
        name: 'Anna Adams',
        age: 31,
        email: 'anna@example.com',
        phone: '555-6666',
        address: '444 Cedar St',
        city: 'Everytown',
        state: 'OR',
        zip: '99002',
        country: 'USA',
        company: 'Design Studio',
        position: 'UX Designer',
        department: 'Creative',
        salary: 70000,
        hireDate: '2022-04-01',
        manager: 'Alice Brown',
        status: 'Active',
        location: 'San Francisco',
        experience: 4,
        education: 'B.A. Graphic Design',
        skills: 'Figma, UX Design',
        certifications: 'None',
        projects: 'Project C',
        performance: 'Good'
    },
    {
        id: 17,
        name: 'George Wright',
        age: 42,
        email: 'george@example.com',
        phone: '555-7777',
        address: '555 Oak St',
        city: 'Anytown',
        state: 'CA',
        zip: '56790',
        country: 'USA',
        company: 'Marketing Hub',
        position: 'Marketing Manager',
        department: 'Marketing',
        salary: 88000,
        hireDate: '2015-05-11',
        manager: 'Linda Martinez',
        status: 'Active',
        location: 'New York',
        experience: 12,
        education: 'B.Sc. Marketing',
        skills: 'SEO, SEM, Content Marketing',
        certifications: 'Google Analytics',
        projects: 'Project I',
        performance: 'Very Good'
    },
    {
        id: 18,
        name: 'Emily Nelson',
        age: 36,
        email: 'emily@example.com',
        phone: '555-8888',
        address: '666 Elm St',
        city: 'Sometown',
        state: 'WA',
        zip: '77890',
        country: 'USA',
        company: 'Tech Corp',
        position: 'HR Specialist',
        department: 'Human Resources',
        salary: 62000,
        hireDate: '2019-09-15',
        manager: 'Patricia Brown',
        status: 'Active',
        location: 'Chicago',
        experience: 6,
        education: 'B.Sc. Human Resources',
        skills: 'Recruitment, Onboarding',
        certifications: 'None',
        projects: 'Project J',
        performance: 'Good'
    },
    {
        id: 19,
        name: 'Sophia King',
        age: 27,
        email: 'sophia@example.com',
        phone: '555-9999',
        address: '777 Pine St',
        city: 'Othertown',
        state: 'NV',
        zip: '11235',
        country: 'USA',
        company: 'Design Studio',
        position: 'Graphic Designer',
        department: 'Creative',
        salary: 65000,
        hireDate: '2020-01-05',
        manager: 'Alice Brown',
        status: 'Active',
        location: 'San Francisco',
        experience: 4,
        education: 'B.A. Fine Arts',
        skills: 'Illustrator, Photoshop',
        certifications: 'Adobe Certified Expert',
        projects: 'Project D',
        performance: 'Good'
    },
    {
        id: 20,
        name: 'Peter Walker',
        age: 44,
        email: 'peter@example.com',
        phone: '555-1010',
        address: '888 Maple St',
        city: 'Somecity',
        state: 'AZ',
        zip: '33457',
        country: 'USA',
        company: 'Finance Corp',
        position: 'Financial Analyst',
        department: 'Finance',
        salary: 91000,
        hireDate: '2018-07-21',
        manager: 'Susan Taylor',
        status: 'Active',
        location: 'Dallas',
        experience: 15,
        education: 'M.Sc. Finance',
        skills: 'Financial Modeling, Forecasting',
        certifications: 'CFA',
        projects: 'Project G',
        performance: 'Excellent'
    }
];

const CustomCell = (props) => {
    const { column, value } = props;

    if (column.name === 'age') {
        return (
            <Table.Cell {...props} style={{ color: value > 30 ? 'red' : 'green' }}>
                {value}
            </Table.Cell>
        );
    }

    return <Table.Cell {...props} />;
};

const CustomGrid = () => {
    const [filters, setFilters] = useState([]);
    const [sorting, setSorting] = useState([]);
    const [currentPage, setCurrentPage] = useState(0);
    const [pageSize, setPageSize] = useState(5);
    const [columnWidths, setColumnWidths] = useState([
        { columnName: 'id', width: 60 },
        { columnName: 'name', width: 150 },
        { columnName: 'age', width: 80 },
        { columnName: 'email', width: 200 },
        { columnName: 'phone', width: 150 },
        { columnName: 'address', width: 200 },
        { columnName: 'city', width: 150 },
        { columnName: 'state', width: 100 },
        { columnName: 'zip', width: 100 },
        { columnName: 'country', width: 150 },
        { columnName: 'company', width: 150 },
        { columnName: 'position', width: 150 },
        { columnName: 'department', width: 150 },
        { columnName: 'salary', width: 100 },
        { columnName: 'hireDate', width: 120 },
        { columnName: 'manager', width: 150 },
        { columnName: 'status', width: 100 },
        { columnName: 'location', width: 150 },
        { columnName: 'experience', width: 150 },
        { columnName: 'education', width: 200 },
        { columnName: 'skills', width: 200 },
        { columnName: 'certifications', width: 200 },
        { columnName: 'projects', width: 200 },
        { columnName: 'performance', width: 150 }
    ]);
    const [hiddenColumnNames, setHiddenColumnNames] = useState([]);

    return (
        <Grid rows={rows} columns={columns}>
            <FilteringState filters={filters} onFiltersChange={setFilters} />
            <IntegratedFiltering />
            <SortingState sorting={sorting} onSortingChange={setSorting} />
            <IntegratedSorting />
            <PagingState
                currentPage={currentPage}
                onCurrentPageChange={setCurrentPage}
                pageSize={pageSize}
                onPageSizeChange={setPageSize}
            />
            <IntegratedPaging />
            <Table cellComponent={CustomCell} />
            <TableColumnResizing columnWidths={columnWidths} onColumnWidthsChange={setColumnWidths} />
            <TableHeaderRow showSortingControls />
            <TableFilterRow />
            <PagingPanel pageSizes={[5, 10, 20]} />
            <TableColumnVisibility
                hiddenColumnNames={hiddenColumnNames}
                onHiddenColumnNamesChange={setHiddenColumnNames}
            />
            <Toolbar />
            <ColumnChooser />
        </Grid>
    );
};

export default CustomGrid;
